openapi: 3.0.0
info:
  title: Home Library Service
  description: Home music library service
  version: 1.0.0

servers:
  - url: /

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        login:
          type: string
        version:
          type: integer
        createdAt:
          type: integer
        updatedAt:
          type: integer
      required:
        - id
        - login
        - version
        - createdAt
        - updatedAt

    Artist:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        grammy:
          type: boolean
      required:
        - id
        - name
        - grammy

    Album:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        year:
          type: integer
        artistId:
          type: string
          format: uuid
          nullable: true
      required:
        - id
        - name
        - year

    Track:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        artistId:
          type: string
          format: uuid
          nullable: true
        albumId:
          type: string
          format: uuid
          nullable: true
        duration:
          type: integer
          description: In seconds
      required:
        - id
        - name
        - duration

    FavoritesResponse:
      type: object
      properties:
        artists:
          type: array
          items:
            $ref: '#/components/schemas/Artist'
        albums:
          type: array
          items:
            $ref: '#/components/schemas/Album'
        tracks:
          type: array
          items:
            $ref: '#/components/schemas/Track'

paths:
  /user:
    get:
      tags: [ Users ]
      summary: Get all users
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      tags: [ Users ]
      summary: Create user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                password:
                  type: string
              required: [ login, password ]
      responses:
        201:
          description: User created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        400:
          description: body does not contain required fields

  /user/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
    get:
      tags: [ Users ]
      summary: Get user by id
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        400:
          description: id is invalid
        404:
          description: User not found
    put:
      tags: [ Users ]
      summary: Update user password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                oldPassword:
                  type: string
                newPassword:
                  type: string
              required: [ oldPassword, newPassword ]
      responses:
        200:
          description: User updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        400:
          description: id is invalid
        403:
          description: oldPassword is wrong
        404:
          description: User not found
    delete:
      tags: [ Users ]
      summary: Delete user
      responses:
        204:
          description: Deleted successfully
        400:
          description: id is invalid
        404:
          description: User not found

  /artist:
    get:
      tags: [ Artist ]
      summary: Get all artists
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Artist'
    post:
      tags: [ Artist ]
      summary: Create artist
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                grammy:
                  type: boolean
              required: [ name, grammy ]
      responses:
        201:
          description: Artist created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Artist'
        400:
          description: Missing required fields

  /artist/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
    get:
      tags: [ Artist ]
      summary: Get artist by id
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Artist'
        400: { description: invalid id }
        404: { description: Artist not found }

    put:
      tags: [ Artist ]
      summary: Update artist
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                grammy:
                  type: boolean
              required: [ name, grammy ]
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Artist'
        400: { description: invalid id }
        404: { description: Artist not found }

    delete:
      tags: [ Artist ]
      summary: Delete artist
      responses:
        204: { description: Deleted }
        400: { description: invalid id }
        404: { description: Artist not found }

  /album:
    get:
      tags: [ Album ]
      summary: Get all albums
      responses:
        200:
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Album'
    post:
      tags: [ Album ]
      summary: Create album
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                year:
                  type: integer
                artistId:
                  type: string
                  format: uuid
                  nullable: true
              required: [ name, year ]
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Album'
        400: { description: Missing fields }

  /album/{id}:
    parameters:
      - name: id
        in: path
        schema:
          type: string
          format: uuid
        required: true
    get:
      tags: [ Album ]
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Album'
        400: { description: invalid id }
        404: { description: Album not found }
    put:
      tags: [ Album ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Album'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Album'
        400: { description: invalid id }
        404: { description: Album not found }
    delete:
      tags: [ Album ]
      responses:
        204: { description: Deleted }
        400: { description: invalid id }
        404: { description: Album not found }

  /track:
    get:
      tags: [ Track ]
      summary: Get all tracks
      responses:
        200:
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Track'
    post:
      tags: [ Track ]
      summary: Create track
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name: { type: string }
                artistId: { type: string, format: uuid, nullable: true }
                albumId: { type: string, format: uuid, nullable: true }
                duration: { type: integer }
              required: [ name, duration ]
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Track'
        400: { description: Missing fields }

  /track/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
    get:
      tags: [ Track ]
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Track'
        400: { description: invalid id }
        404: { description: Track not found }
    put:
      tags: [ Track ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Track'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Track'
        400: { description: invalid id }
        404: { description: Track not found }
    delete:
      tags: [ Track ]
      responses:
        204: { description: Deleted }
        400: { description: invalid id }
        404: { description: Track not found }

  /favs:
    get:
      tags: [ Favorites ]
      summary: Get all favorites
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FavoritesResponse'

  /favs/track/{id}:
    parameters:
      - name: id
        in: path
        schema:
          type: string
          format: uuid
        required: true
    post:
      tags: [ Favorites ]
      responses:
        201: { description: Added }
        400: { description: invalid id }
        422: { description: Track does not exist }
    delete:
      tags: [ Favorites ]
      responses:
        204: { description: Deleted }
        400: { description: invalid id }
        404: { description: Not in favorites }

  /favs/album/{id}:
    parameters:
      - name: id
        in: path
        schema:
          type: string
          format: uuid
    post:
      tags: [ Favorites ]
      responses:
        201: { description: Added }
        400: { description: invalid id }
        422: { description: Album does not exist }
    delete:
      tags: [ Favorites ]
      responses:
        204: { description: Deleted }
        400: { description: invalid id }
        404: { description: Not in favorites }

  /favs/artist/{id}:
    parameters:
      - name: id
        in: path
        schema:
          type: string
          format: uuid
    post:
      tags: [ Favorites ]
      responses:
        201: { description: Added }
        400: { description: invalid id }
        422: { description: Artist does not exist }
    delete:
      tags: [ Favorites ]
      responses:
        204: { description: Deleted }
        400: { description: invalid id }
        404: { description: Not in favorites }
